# Generated by Django 3.2.25 on 2024-04-11 00:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20240411_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('fixed', 'Fixed Rate'), ('hourly', 'Hourly Rate')], default='fixed', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_duration_hours', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service_images')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.business')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='accounts.category')),
            ],
        ),
    ]
