# Generated by Django 4.2.8 on 2024-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
