# Generated by Django 3.2.25 on 2024-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.IntegerField(default=1, help_text='Duration of the booking in hours.'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_duration_hours',
            field=models.IntegerField(blank=True, help_text='Minimum duration in hours for bookings, applicable for hourly priced services.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
