# Generated by Django 3.2.25 on 2024-04-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240411_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='business',
        ),
    ]
