# Generated by Django 3.2.25 on 2024-04-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_booking_price'),
        ('accounts', '0008_auto_20240411_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='checkout.booking'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
