# Generated by Django 4.2.8 on 2024-04-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
